version: "2"
services:
  cqpweb:
   image: rahonabe/cqpweb
   env_file: ./secrets.env
   domainname: ${DOMAINNAME}
   hostname: ${FIRSTNAME}-CQPweb
   build: 
      context: ./cqpweb
   ports:
       - 80:80
   volumes:
       - ./${FIRSTNAME}-container/cwb/corpora:/var/corpora
       - ./${FIRSTNAME}-container/cwb/registry:/usr/local/share/cwb/registry
       - ./${FIRSTNAME}-container/cqpweb/upload:/var/cqpweb/upload
       - ./${FIRSTNAME}-container/cqpweb/data:/var/www/html
       - ./${FIRSTNAME}-container/cqpweb/tmp:/var/cqpweb/tmp
  sql:
    image: mariadb
    env_file: ./secrets.env
    domainname: ${DOMAINNAME}
    hostname: ${FIRSTNAME}-sql
    volumes:
      - ./${FIRSTNAME}-container/lib/mysql:/var/lib/mysql
    volumes_from:
        - cqpweb
